#!/bin/bash

echo "--> BUILDING ehlertij/thumbor"
docker build --pull -f thumbor/Dockerfile -t ehlertij/thumbor thumbor/
# introspecting version by running the built image
THUMBOR_VERSION=`docker run --rm ehlertij/thumbor bash -c "pip freeze |grep ^thumbor== | cut -d= -f 3"`
echo "THUMBOR VERSION: $THUMBOR_VERSION"

echo "--> TAGGING ehlertij/thumbor:$THUMBOR_VERSION"
docker tag ehlertij/thumbor ehlertij/thumbor:$THUMBOR_VERSION
echo "--> TAGGING ehlertij/thumbor:latest"
docker tag ehlertij/thumbor ehlertij/thumbor:latest

