version: '3'
services:
  thumbor:
    image: 'ehlertij/thumbor:latest'
    environment:
      # VIRTUAL_HOST is picked up by nginx-proxy. Here it's set for localhost
      # but you usually need to point it to your domain, e.g. thumbor.example.com
      - VIRTUAL_HOST=localhost
      # THUMBOR_NUM_PROCESSES control how many processes run inside the container
      # Normally this is set in connection with the number of CPU cores
      # Note however that you can also use the docker-compose scale option to dynamically
      # scale your thumbor instances
      - THUMBOR_NUM_PROCESSES=1
      # this would allow CORS from any origin (you can restrict to specific origins if you want)
      - CORS_ALLOW_ORIGIN=*
      # returns a webp image if browser Accept headers match
      - AUTO_WEBP=True
      - QUALITY=95
      - WEBP_QUALITY=100
      - ENGINE=graphicsmagick_engine
      - LOG_LEVEL=debug
      - ALLOW_ANIMATED_GIFS=True
      - USE_GIFSICLE_ENGINE=True
      # Basic thumbor setup to cache both original images and results (after manipulation)
      # nginx-proxy would detect if there's a cached version and serve it for you automatically
      # (this greatly speeds up and saves on CPU)
    restart: always
    networks:
      - app
    ports:
      - '8080:80'
networks:
  app:
    driver: bridge
