#!/bin/bash

# introspecting version by running the built image
THUMBOR_VERSION=`docker run --rm ehlertij/thumbor bash -c "pip freeze |grep ^thumbor== | cut -d= -f 3"`
echo "THUMBOR VERSION: $THUMBOR_VERSION"

echo "--> pushing ehlertij/thumbor"
docker push ehlertij/thumbor:latest
docker push ehlertij/thumbor:$THUMBOR_VERSION
